### ISSUE TITLE
Scoped npm packages (paths starting with @ character)

### ISSUE THREAD

**Issue by dy-dx** [aziz/SublimeHyperClick#16]
SublimeHyperClick doesn't seem to work for [scoped packages](https://docs.npmjs.com/misc/scope), for example:
```js
import { storiesOf, action } from '@kadira/storybook';
import { withKnobs, boolean, text } from '@kadira/storybook-addon-knobs';
```

**Comment by dy-dx** [comment]
Wow that was fast. Thank you!

**Comment by dgirgenti** [comment]
I'm confused -- this isn't working for me. My codebase recently added aliases and now HyperClick no longer works

For example, we have a `@core` alias that maps to `<project root>/src/sdk/features/core`
