### ISSUE TITLE
New resolver

### ISSUE THREAD

**Issue by volkerdobler** [aziz/SublimeHyperClick#17]
Hi,

I did not understand how to include a new resolver in the module.

I have a language where I have to include the file ending to my script (e.g. #include "filename.ext";)
If I use the original GeneralPathResolver, this adds the extention again and so it looks for "filename.ext.ext" which does not exists).

So I have written a new gessQ_resolver_path.py but I did not understand, how do I include this new file in the Hyperclick or sublime system? 

Do I have to change the path_resolver.py in hyperclick.sublime-package also? (and include the new syntax as new if-branch?)
And where do I save the (new) path_resolver.py or the new gessQ_resolver_path.py? In my User-Dir or in my directory, where the gessQ.sublime-syntax is stored? Or in the original %APPDATA% directory (and do I have to unpack the hyperclick.sublime-package)?

As you can see, many questions - but hopefully only a few answers :-)

Thanks for any hint and for the good module,
Volker

**Comment by aziz** [comment]
Did you manage to figure it out? It would be easier to help if you give us a link to your fork. 
It's hard to talk about code without looking at the source.

**Comment by volkerdobler** [comment]
Hi aziz,

sorry, sure, I can share the small piece of code - but it's not a problem of the code (I think :-) ) but how to include in in your system. I think I even did not need to write "new" code, as it is already there, but not with the right ending.

Ok, here we go:

I have a language which has the ending ".q". In this files, I am working with #include commands to include other pieces of code. The lines look like "#include 'includedfile.q'".

I "wrote" the following piece of code - very close to the Sass Example you provided:

```
# -*- coding: utf-8 -*-
from os import path

class gessQPathResolver:
    def __init__(self, str_path, current_dir, roots, lang, settings):
        self.str_path = str_path
        self.current_dir = current_dir
        self.lang = lang
        self.settings = settings
        self.roots = roots
        self.valid_extensions = settings.get('valid_extensions', {})[lang]

    def resolve(self):
        combined = path.realpath(path.join(self.current_dir, self.str_path))
        # matching ../variables/palette to ../variables/palette.scss
        for ext in self.valid_extensions:
            file_path = combined
            if path.isfile(file_path):
                return file_path

        # matching ../variables/palette to ../variables/_palette.scss
        pathname, filename = path.split(self.str_path)
        combined = path.realpath(path.join(self.current_dir, pathname, '_' + filename))
        for ext in self.valid_extensions:
            file_path = combined
            if path.isfile(file_path):
                return file_path
```

The only differences are - new name for the resolver and no "+ ext" as the filename should include the .q

I put this file as gessq_path_resolver.py in my user-dir - nothing happen. Then I looked in your code and found "path_resolver.py" which includes the different resolvers. And there, I found the "if" commands for JS, SASS and PHP in the newest version.

```
# -*- coding: utf-8 -*-
from os import path
from .js_path_resolver import JsPathResolver
from .sass_path_resolver import SassPathResolver
from .path_generic_subfolder_resolver import GenericSubfolderResolver


class HyperClickPathResolver:
    def __init__(self, str_path, current_file, roots, lang, settings):
        current_dir = path.dirname(path.realpath(current_file))
        if lang == 'js':
            self.resolver = JsPathResolver(str_path, current_dir, roots, lang, settings)
        elif lang == 'sass':
            self.resolver = SassPathResolver(str_path, current_dir, roots, lang, settings)
        else:
            self.resolver = GenericSubfolderResolver(str_path, current_dir, roots, lang, settings)

    def resolve(self):
        return self.resolver.resolve()

```
Now my questions: 
Do I have to copy this file and modify it also - and where should I put this file - in the user directory or anywhere else?
Is there any other way of including new languages than modifying this path_resolver.py, as you did not mentioned it in your documentation. 
The "GenericSubfolderResolver" works, but it includes the "extension" which I did not want/need.

Current workaround (for me and my language script file):
I modified the setting files to not include the extension from my filename.

```
{
  "supported_syntaxes": {
    "gessQ": [
      "gessQ.tmLanguage"
    ]
  },
  "import_line_regex": {
    "gessQ": [
      "^#include\\s+['\"](.+)\\.q['\"];$"
    ]
  },
  "valid_extensions": {
    "gessQ": ["q"]
  },
  "vendor_dirs": {
    "gessQ": ["."]
  },

}

```

But is this an "official" way of including additional languages? Than, I did not understand the remark about the modification of the SASSresolver "template".

Hope my long explanation is clear?

Thanks for this helpful software, I like it a lot (and currently, it works for me with this "workaround".

Volker

**Comment by volkerdobler** [comment]
P.S. my personal preference would be, if there will be a "resolver" setting in the hyper_click.sublime-settings file in future versions (maybe it is already there, but I did not find it).

Then I can have my own resolver file for each language I need.

**Comment by cristianl** [comment]
https://github.com/aziz/SublimeHyperClick/issues/11#issuecomment-572751563
