### ISSUE TITLE
bug on hover event

### ISSUE THREAD

**Issue by eparisio** [aziz/SublimeHyperClick#21]
Hi, i found some problem with the hover and the cursor position event + arrows.

If you hover an element with the cursor on a not-matching line it works fine.
But, if you have the cursor on a matching line the hover effect links always to the cursor position file.

if you hover on a missing file matching the first time you open or focus a file, the other files continue to print the red unclickable arrow, as if the last directory remain in cache for the arrow preview, if you set the cursor on a not-matching line, than it start to works again for the next hovering/cursored file or if you lose focus of the file.

the same is the opposite, if you hover a ok file, and than you hover on a missing file the arrow remains green, it reset as in the other case.

in any case the cursor position actually wins over every other event.

**Comment by braver** [comment]
> But, if you have the cursor on a matching line the hover effect links always to the cursor position file.

I cannot reproduce this?

> if you hover on a missing file matching the first time you open or focus a file, the other files continue to print the red unclickable arrow

Nope, not on my machine. Maybe the ST4 build I'm on solved some issues with the ViewEventListener or something? Or, a lot of work was done on this plugin since this report, so maybe it was fixed but never closed?
