### ISSUE TITLE
why i can't see the green arrow 

### ISSUE THREAD

**Issue by xwillmadeit** [aziz/SublimeHyperClick#3]
why i can't see the green arrow

**Comment by aziz** [comment]
Please provide more information like your sublime version, plugin version and the OS

**Comment by aziz** [comment]
It's also does not show the annotations if the file is dirty and you have un-saved stuff

**Comment by ifedapoolarewaju** [comment]
I can't get this to work on my machine either. I use MacOS Sierra and SublimeText version `3126`.

It simply does nothing like I never installed it.

**Comment by steffenagger** [comment]
@ifedapoolarewaju do you by any change write your code with _no trailing semicolons_? That was my problem, all regexes in the config are expressions including the trailing semicolon...

@aziz maybe update the standard config-regexes to not care about syntax preferences?
other than that, just the plugin I was looking for 👍

**Comment by steffenagger** [comment]
oops, not entirely true... I think it's actually only an issue with `require`..?
Its current regex is: `".+require\\(['\"](.+)['\"]\\).+"`
I changed it to be: `".*require\\(['\"](.+)['\"]\\).*"` and it worked (both beginning and end has gone from `.+` to `.*`).
