### ISSUE TITLE
add cmd/ctrl click on the configurations

### ISSUE THREAD

**Issue by eparisio** [aziz/SublimeHyperClick#32]
Hi,
recentry i found a method to open the the files with key+click, it can be usefull add it to the standard config (at least create the file for the plugin) or add a note on the readme

You need to add this lines:

`[
	{ "button": "button1", "modifiers": ["ctrl", "shift"], "command": "hyper_click_jump", "press_command": "drag_select" },
]`

in this file:
`\Packages\User\Default (Windows).sublime-mousemap`

eventually you need to create this file that is not a default one.
the key combination can be customize, i add a windows configuration but it should work with all systems

**Comment by codeclown** [comment]
Coincidentally I implemented something like this just recently. Here's a PR https://github.com/aziz/SublimeHyperClick/pull/34

**Comment by cristianl** [comment]
cmd/ctrl+alt+click added from https://github.com/aziz/SublimeHyperClick/pull/34
