### ISSUE TITLE
Lookup paths or aliases?

### ISSUE THREAD

**Issue by cadoan** [aziz/SublimeHyperClick#36]
Hi,

Firstly thanks for the great Sublime plugin.

I'm working on a project with aliased deps like this:
`import blah from 'theproject/metrics/utils'`

The file is actually in:
`<root>/assets/js/metrics/utils`

How can I edit my prefs file to support that?

Thanks!
Chris.

**Comment by kenberkeley** [comment]
+1

**Comment by dy** [comment]
+1

**Comment by anru** [comment]
you need `lookup_paths` setting which works like NODE_PATH variable for node.js

**Comment by mkorostoff** [comment]
@anru could you maybe elaborate or provide an example how to use the `lookup_paths` setting?

p.s. I love your plugin, awesome work

**Comment by anru** [comment]
About editing settings: https://github.com/aziz/SublimeHyperClick#settings

`lookup_paths` is array of strings, works exactly as paths in NODE_PATH env variable works for node itself

**Comment by anru** [comment]
Also see https://github.com/aziz/SublimeHyperClick/issues/27#issuecomment-340384812

**Comment by mkorostoff** [comment]
thanks

**Comment by arryanggaputra** [comment]
@anru  Do you have example for module alias?

**Comment by eparisio** [comment]
> @anru Do you have example for module alias?

you can add 
```
"lookup_paths": {
    "js": ["<root>/assets/js/"],
```

dunno how to replace ```theproject``` i did't find any replace in the code
other than this it should take the path as ```<root>/assets/js/theproject/metrics/utils```

i did something similar in the jstl resolver but the path were on the file, so i take them with a regex.

**Comment by cristianl** [comment]
Alias support shipped in [1.11.0](https://github.com/aziz/SublimeHyperClick/releases/tag/1.11.0). Lookup paths are [also configurable](https://github.com/aziz/SublimeHyperClick#project-settings-example)
