### ISSUE TITLE
Support for Vuejs single file components

### ISSUE THREAD

**Issue by reignmaker** [aziz/SublimeHyperClick#39]
Hello,

Thank you for such usefull plugin. I'm working with Vue.js and would like to have this plugin work with `.vue` files. Or can I adjust settings by myself so that plugin will recognize all `import`s?

Thanks.

**Comment by RaphaelDDL** [comment]
`Preferences > Package Settings > HyperClick > Settings`:

It'll show you a split screen with Default config on the left and User config on the right. You'll see something like this on Default:

    "supported_syntaxes": {
        "js": [
           "ecmascript.sublime-syntax",
          "JavaScript.sublime-syntax",
          "JavaScript (Babel).sublime-syntax",
          "JavaScriptNext.tmLanguage"
        ]
    }

On the right side will be shown an empty object. Sublime does not merge user array with default, so you need to re-declare `js` with the default settings plus any syntax you want. 

In my case, I installed `Vue Syntax Highlight`, so my user setting for HyperClick is like this:

    "supported_syntaxes": {
        "js": [
          "Vue Component.sublime-syntax",
           "ecmascript.sublime-syntax",
          "JavaScript.sublime-syntax",
          "JavaScript (Babel).sublime-syntax",
          "JavaScriptNext.tmLanguage"
        ]
    }


Now the hook for opening the file works on my `.vue` file:
![screen shot 2018-10-18 at 7 08 54 pm](https://user-images.githubusercontent.com/1087109/47187120-4a543880-d309-11e8-9747-61192adafcbd.png)

**Comment by reignmaker** [comment]
Brilliant! Thank you very much.

**Comment by anru** [comment]
now HyperClick supports vue files without any custom configuration
