### ISSUE TITLE
misplacing of the arrow 

### ISSUE THREAD

**Issue by MKruschke** [aziz/SublimeHyperClick#4]
Hi,
I just tried these awesome plugin on my Mac with Sublime (Build 3126) and there the arrow shows up below the selected import line (see attached screenshot). Normally there is no blank line between these import directives. 

Best Mirko

![section_spec_jsx_ _cardonis-ui](https://cloud.githubusercontent.com/assets/1651782/20617951/9b0450d8-b2ec-11e6-8199-8e27dee9a391.png)

**Comment by MKruschke** [comment]
I just disabled the Material Theme that I'm using and than it's all fine, but I would be nice if it will work with my favorite Theme ;)

**Comment by aziz** [comment]
Fixed in 1.0.3
