### ISSUE TITLE
Support for Dart language

### ISSUE THREAD

**Issue by zanuka** [aziz/SublimeHyperClick#45]
Excellent package. Dart support would be awesome 🚀

**Comment by cristianl** [comment]
Added basic support in https://github.com/aziz/SublimeHyperClick/commit/4a9ca8b48aa40cf3268a2cf7fed7607d3b7fdd6c. It will ship in the next release (1.11.0)

HyperClick will recognize local files, but not namespaced modules like `'dart:math'` or `'package:my-package/foo.dart'`

**Comment by cristianl** [comment]
Shipped in [1.11.0](https://github.com/aziz/SublimeHyperClick/releases/tag/1.11.0)
