### ISSUE TITLE
Add a way to support webpack aliases

### ISSUE THREAD

**Issue by adriantoine** [aziz/SublimeHyperClick#5]
Hi!

The project I'm working on is using a lot of [webpack aliases](https://webpack.github.io/docs/configuration.html#resolve-alias) which makes this plugin unfortunately unusable for me.

It would be great to have a way to configure the plugin so that I can set up aliases.

**Comment by aziz** [comment]
<RANT>
I believe it's wrong to use that feature of webpack cause it breaks everything as soon as you move away from webpack. 
</RANT>

You can easily add it to the javascript resolver and send a pull request.

**Comment by TylerK** [comment]
@adriantoine A work around would be to add those aliased directories to the vendor directory array in the settings.

**Comment by dgirgenti** [comment]
@TylerK can you elaborate please? My codebase recently implemented aliases and now HyperClick isn't working for me

For example, one of our new aliases `@core` points to `<project root>/src/sdk/features/core`, I can't figure out how to get HyperClick to respect these aliases.
