### ISSUE TITLE
To port to Cud

### ISSUE THREAD

**Issue by Alexey-T** [aziz/SublimeHyperClick#6]
Tks for plugin
I want to port to CudaText, can you help? To port, i need some .py file with API which can get full filename of clicked pos.
E.g. func, parameters:

- buffer text
- filename of buffer (e.g. "/path/myfile.js")
- line/col index, for clicked pos

result:

- None if cannot find file
- filename if can find file

**Comment by aziz** [comment]
Sorry I can't help, but feel free to use this codebase however you need
