### ISSUE TITLE
jump typescript file

### ISSUE THREAD

**Issue by Straw94** [aziz/SublimeHyperClick#61]
when i click goto file, it will jump to definition file, but it's js file
how to configure jump to index.ts ?

**Comment by braver** [comment]
It really helps to have an example project or bit of code to look at. I can probably help fix it, but don’t have a working TS at hand right now.

**Comment by Straw94** [comment]
how to jump to dom type in typescript?
such as WebSocketEventMap...
Unfortunately, when I click, nothing happens
