### ISSUE TITLE
Plugin suddenly stopped working

### ISSUE THREAD

**Issue by abhishiv** [aziz/SublimeHyperClick#72]
Hey there, just noticed that hyperclick suddenly stopped working

Using sublime on macos
Nothing in logs
Using in typescript

Unfortunately not much information else since there are no errors in the logs

**Comment by cristianl** [comment]
Does it work on a JS file? What is the output when you run `view.scope_name(view.sel()[0].begin())` in the console?

**Comment by abhishiv** [comment]
Hey @cristianl thanks for your reply.

Yeah in js with require it seems to be working. 

```
>>> view.scope_name(view.sel()[0].begin())
'source.tsx meta.function.tsx meta.block.tsx '
```

this is the output I got

**Comment by cristianl** [comment]
> 'source.tsx meta.function.tsx meta.block.tsx '

Yep, HyperClick looks for scope `source.ts`. You can try @braver's fork of the TypeScript syntax package https://github.com/braver/TypeScriptSyntax

**Comment by abhishiv** [comment]
Hmm, weird. I already have been using @barvers fork
![TypeScript_Syntax_and_popup_and_index_tsx_—_unikernel_src_bus_—_grati_co_and_Plugin_suddenly_stopped_working_·_Issue__72_·_aziz_SublimeHyperClick](https://user-images.githubusercontent.com/37350/97885413-9ecb8480-1d27-11eb-9827-a546c3f1be89.png)

Maybe something in my installation is overriding it.

Edit: Ah now I understand, it needs to have file set as ts not tsx. Doing that fixes it. Thanks!
