### ISSUE TITLE
Difficulty with project-level aliases settings format for 2.0

### ISSUE THREAD

**Issue by rcherny** [aziz/SublimeHyperClick#73]
Love the plugin, and have been using it for years, thanks. 

However, my project-level alias settings aren't working since the 2.0 upgrade. I updated the settings to what I believe should be the new format for 2.0.

My settings for mapped aliases on my project are as follows:

```json
	"settings": {
		"HyperClick": {
			"scopes": {
				"source.js": {
					"aliases": {
						"@data": "src/data",
						"@shared": "src/components/shared",
						"@templates": "src/templates",
						"@components": "src/components"
					}
				},
				"source.sass": {
					"aliases": {
						"@utils": "src/layouts/styles",
						"@pageStyles": "src/pages/styles"
					}
				}
			}
		},
```

I just get the red [x] icon next to each import at this point.

Am I doing something wrong with the new syntax?

**Comment by cristianl** [comment]
Temporary fix: replace `"source.js"` with `"source.ts, source.js"` and `"source.sass"` with `"source.scss, source.sass"`

(I actually introduced this bug a [few commits ago](https://github.com/aziz/SublimeHyperClick/commit/9013f0f3bb4718fbe07159333ad1daf032e12f71) to prevent TS/JS and SCSS/Sass settings from getting out of sync, but this probably should be handled internally)

**Comment by cristianl** [comment]
@rcherny Sorry, the issue is something else altogether. The plugin was loading the outdated (pre-v2) settings. [2.2.0](https://github.com/aziz/SublimeHyperClick/releases/tag/2.2.0) fixes it.

Package Control caches the list of packages for a few hours. You may need to [install from the repo instead](https://packagecontrol.io/docs/usage)
