### ISSUE TITLE
not treat index file of folder

### ISSUE THREAD

**Issue by iahu** [aziz/SublimeHyperClick#75]
and the look up system not treat index file of folder.

```js
import A from 'lib/a'; // say as a is a folder name, and `/lib/a/index.[extname]` should be treat as `/lib/a`
```

**Comment by dbrekalo** [comment]
version 2.3.0. which fixes this is not currently available via [package control](https://packagecontrol.io/packages/HyperClick)?

**Comment by cristianl** [comment]
[2.3.0](https://github.com/aziz/SublimeHyperClick/releases/tag/2.3.0) is now available on Package Control.
