### ISSUE TITLE
Alias "@" not working

### ISSUE THREAD

**Issue by Niekes** [aziz/SublimeHyperClick#82]
Hi,

I have the following setup:

```json
        "hyper_click": {
            "aliases": {
                "js": {
                    "@": "./src",
                }
            }
        }
```

```js
// I want to import like this:
import config from '@/config';
```

Unfortunately HyperClick is not able to resolve "@" to "src" or "./src". What am I doing wrong?

**Comment by jfcherng** [comment]
It looks like you are still using the old v1 version settings... Simply check the new default settings https://github.com/aziz/SublimeHyperClick/blob/master/HyperClick.sublime-settings (but wouldn't it auto be opened side-by-side when you config the settings?)

---

Tested `@` is working well on my side in JS.

**Comment by Niekes** [comment]
Works!

I changed it to:

```json
"HyperClick": {
    "scopes": {
        "source.js | source.jsx | source.ts | source.tsx": {
            "aliases": {
                "@": "src"
            }
        }
    }
}
```

Thank you!
