### ISSUE TITLE
hyperlink v. 2.5.0. "aliases": "@" don't work any more  in vuejs project File not found. 2.4.0 works

### ISSUE THREAD

**Issue by danilovmy** [aziz/SublimeHyperClick#91]
"HyperClick": {
			"scopes": {
				"source.js | source.jsx | source.ts | source.tsx": {
					"aliases": {"@" : "C:\\projects\\maproject\\vuejsfolder\\",},
				},
			},
		},

**Comment by jfcherng** [comment]
I can confirm `aliases` is not working as expected. The offending commit is 66343acc4f91b07244e6df91161b184afef89b6f  from #84.

**Comment by jfcherng** [comment]
By using `git bisect`, the offending commit is https://github.com/aziz/SublimeHyperClick/commit/66343acc4f91b07244e6df91161b184afef89b6f
